[2021-03-25 14:40:47,744] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Inference-Pipeline.preprocess 2021-03-25T21:40:33.990412+00:00 [queued]>
[2021-03-25 14:40:47,759] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Inference-Pipeline.preprocess 2021-03-25T21:40:33.990412+00:00 [queued]>
[2021-03-25 14:40:47,759] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-25 14:40:47,759] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-25 14:40:47,759] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-25 14:40:47,772] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): preprocess> on 2021-03-25T21:40:33.990412+00:00
[2021-03-25 14:40:47,784] {standard_task_runner.py:52} INFO - Started process 4078 to run task
[2021-03-25 14:40:47,791] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Inference-Pipeline', 'preprocess', '2021-03-25T21:40:33.990412+00:00', '--job-id', '31', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_inference.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpfz8xiirv', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpk7u5sq6h']
[2021-03-25 14:40:47,794] {standard_task_runner.py:77} INFO - Job 31: Subtask preprocess
[2021-03-25 14:40:47,838] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Inference-Pipeline.preprocess 2021-03-25T21:40:33.990412+00:00 [running]> on host prathyushas-mbp.home
[2021-03-25 14:40:47,868] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Inference-Pipeline
AIRFLOW_CTX_TASK_ID=preprocess
AIRFLOW_CTX_EXECUTION_DATE=2021-03-25T21:40:33.990412+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-25T21:40:33.990412+00:00
[2021-03-25 14:40:47,873] {logging_mixin.py:104} INFO - ['CELTF', 'ACFN', 'KGFHF', 'BLFS', 'IRIX', 'BMMJ', 'GHLD', 'TME']
[2021-03-25 14:40:48,833] {credentials.py:1217} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2021-03-25 14:41:07,440] {taskinstance.py:1455} ERROR - Cannot connect to host edgarfile-storage.s3.amazonaws.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')]
Traceback (most recent call last):
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 989, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1017, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/sslproto.py", line 530, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 774, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/dags/edgar_inference.py", line 135, in preprocess
    final_df.to_csv(path,index=False)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/pandas/core/generic.py", line 3402, in to_csv
    storage_options=storage_options,
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1083, in to_csv
    csv_formatter.save()
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 234, in save
    storage_options=self.storage_options,
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/pandas/io/common.py", line 563, in get_handle
    storage_options=storage_options,
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/pandas/io/common.py", line 334, in _get_filepath_or_buffer
    filepath_or_buffer, mode=fsspec_mode, **(storage_options or {})
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/fsspec/core.py", line 438, in open
    **kwargs,
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/fsspec/core.py", line 291, in open_files
    [fs.makedirs(parent, exist_ok=True) for parent in parents]
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/fsspec/core.py", line 291, in <listcomp>
    [fs.makedirs(parent, exist_ok=True) for parent in parents]
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/s3fs/core.py", line 614, in makedirs
    self.mkdir(path, create_parents=True)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/fsspec/asyn.py", line 121, in wrapper
    return maybe_sync(func, self, *args, **kwargs)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/fsspec/asyn.py", line 100, in maybe_sync
    return sync(loop, func, *args, **kwargs)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/fsspec/asyn.py", line 71, in sync
    raise exc.with_traceback(tb)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/fsspec/asyn.py", line 55, in f
    result[0] = await future
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/s3fs/core.py", line 599, in _mkdir
    await self.s3.create_bucket(**params)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/aiobotocore/client.py", line 141, in _make_api_call
    operation_model, request_dict, request_context)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/aiobotocore/client.py", line 160, in _make_request
    return await self._endpoint.make_request(operation_model, request_dict)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 91, in _send_request
    exception):
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 200, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/aiobotocore/hooks.py", line 29, in _emit
    response = handler(**kwargs)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 156, in _do_get_response
    http_response = await self._send(request)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 242, in _send
    request.method, url=url, headers=headers_, data=data, proxy=proxy)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/aiohttp/client.py", line 521, in _request
    req, traces=traces, timeout=real_timeout
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/aiohttp/connector.py", line 1032, in _create_direct_connection
    client_error=client_error,
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/aiohttp/connector.py", line 971, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host edgarfile-storage.s3.amazonaws.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')]
[2021-03-25 14:41:07,470] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=EDGAR-Inference-Pipeline, task_id=preprocess, execution_date=20210325T214033, start_date=20210325T214047, end_date=20210325T214107
[2021-03-25 14:41:07,530] {local_task_job.py:146} INFO - Task exited with return code 1
