[2021-03-25 14:23:42,322] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Inference-Pipeline.preprocess 2021-03-25T21:23:27.575703+00:00 [queued]>
[2021-03-25 14:23:42,331] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Inference-Pipeline.preprocess 2021-03-25T21:23:27.575703+00:00 [queued]>
[2021-03-25 14:23:42,331] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-25 14:23:42,331] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-25 14:23:42,331] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-25 14:23:42,342] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): preprocess> on 2021-03-25T21:23:27.575703+00:00
[2021-03-25 14:23:42,346] {standard_task_runner.py:52} INFO - Started process 3204 to run task
[2021-03-25 14:23:42,355] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Inference-Pipeline', 'preprocess', '2021-03-25T21:23:27.575703+00:00', '--job-id', '11', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_inference.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmp9ogueho3', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmp1l54oujx']
[2021-03-25 14:23:42,356] {standard_task_runner.py:77} INFO - Job 11: Subtask preprocess
[2021-03-25 14:23:42,394] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Inference-Pipeline.preprocess 2021-03-25T21:23:27.575703+00:00 [running]> on host prathyushas-mbp.home
[2021-03-25 14:23:42,424] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Inference-Pipeline
AIRFLOW_CTX_TASK_ID=preprocess
AIRFLOW_CTX_EXECUTION_DATE=2021-03-25T21:23:27.575703+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-25T21:23:27.575703+00:00
[2021-03-25 14:23:42,430] {logging_mixin.py:104} INFO - ['CELTF', 'ACFN', 'KGFHF', 'BLFS', 'IRIX', 'BMMJ', 'GHLD', 'TME']
[2021-03-25 14:23:42,534] {taskinstance.py:1455} ERROR - name 'jsonobject_key' is not defined
Traceback (most recent call last):
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/edgar4_env/lib/python3.7/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/dags/edgar_inference.py", line 131, in preprocess
    jsonpath = 's3://{}/{}/{}'.format(bucket_name, prefix, jsonobject_key)
NameError: name 'jsonobject_key' is not defined
[2021-03-25 14:23:42,540] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=EDGAR-Inference-Pipeline, task_id=preprocess, execution_date=20210325T212327, start_date=20210325T212342, end_date=20210325T212342
[2021-03-25 14:23:42,579] {local_task_job.py:146} INFO - Task exited with return code 1
