[2021-03-25 14:58:23,173] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Inference-Pipeline.Prediction 2021-03-25T21:57:57.970562+00:00 [queued]>
[2021-03-25 14:58:23,183] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Inference-Pipeline.Prediction 2021-03-25T21:57:57.970562+00:00 [queued]>
[2021-03-25 14:58:23,183] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-25 14:58:23,183] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-25 14:58:23,183] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-25 14:58:23,191] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): Prediction> on 2021-03-25T21:57:57.970562+00:00
[2021-03-25 14:58:23,193] {standard_task_runner.py:52} INFO - Started process 5065 to run task
[2021-03-25 14:58:23,202] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Inference-Pipeline', 'Prediction', '2021-03-25T21:57:57.970562+00:00', '--job-id', '43', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_inference.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmplsddvi94', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpwjd5laq3']
[2021-03-25 14:58:23,204] {standard_task_runner.py:77} INFO - Job 43: Subtask Prediction
[2021-03-25 14:58:23,252] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Inference-Pipeline.Prediction 2021-03-25T21:57:57.970562+00:00 [running]> on host prathyushas-mbp.home
[2021-03-25 14:58:23,289] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Inference-Pipeline
AIRFLOW_CTX_TASK_ID=Prediction
AIRFLOW_CTX_EXECUTION_DATE=2021-03-25T21:57:57.970562+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-25T21:57:57.970562+00:00
[2021-03-25 14:59:43,634] {logging_mixin.py:104} WARNING - /Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/dags/edgar_inference.py:167 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2021-03-25 14:59:43,639] {logging_mixin.py:104} WARNING - /Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/airflow/dags/edgar_inference.py:168 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2021-03-25 15:00:27,780] {python.py:118} INFO - Done. Returned value was: None
[2021-03-25 15:00:27,791] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=EDGAR-Inference-Pipeline, task_id=Prediction, execution_date=20210325T215757, start_date=20210325T215823, end_date=20210325T220027
[2021-03-25 15:00:27,812] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-25 15:00:27,844] {local_task_job.py:146} INFO - Task exited with return code 0
