[2021-04-02 00:22:31,024] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: CMAPS_SNOWFLAKE_INGESTION.DataExtraction 2021-04-02T04:20:22+00:00 [queued]>
[2021-04-02 00:22:31,034] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: CMAPS_SNOWFLAKE_INGESTION.DataExtraction 2021-04-02T04:20:22+00:00 [queued]>
[2021-04-02 00:22:31,035] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-02 00:22:31,035] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-02 00:22:31,035] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-02 00:22:31,042] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): DataExtraction> on 2021-04-02T04:20:22+00:00
[2021-04-02 00:22:31,045] {standard_task_runner.py:52} INFO - Started process 9522 to run task
[2021-04-02 00:22:31,053] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'CMAPS_SNOWFLAKE_INGESTION', 'DataExtraction', '2021-04-02T04:20:22+00:00', '--job-id', '34', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/cmaps_pipeline.py', '--cfg-path', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmpjrwyysf6', '--error-file', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmpd6m_uuv4']
[2021-04-02 00:22:31,056] {standard_task_runner.py:77} INFO - Job 34: Subtask DataExtraction
[2021-04-02 00:22:31,095] {logging_mixin.py:104} INFO - Running <TaskInstance: CMAPS_SNOWFLAKE_INGESTION.DataExtraction 2021-04-02T04:20:22+00:00 [running]> on host 152.1.168.192.in-addr.arpa
[2021-04-02 00:22:31,123] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=CMAPS_SNOWFLAKE_INGESTION
AIRFLOW_CTX_TASK_ID=DataExtraction
AIRFLOW_CTX_EXECUTION_DATE=2021-04-02T04:20:22+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-04-02T04:20:22+00:00
[2021-04-02 00:22:31,137] {logging_mixin.py:104} WARNING - /Users/harika/Desktop/CSYE_7245/Assignment3/FastAPI/airflow/dags/cmaps_pipeline.py:23 ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
[2021-04-02 00:22:36,492] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 9522
[2021-04-02 00:22:36,513] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-04-02 00:22:36,534] {taskinstance.py:1455} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/harika/Desktop/CSYE_7245/Assignment3/FastAPI/airflow/dags/cmaps_pipeline.py", line 23, in DataExtraction
    df1=pd.read_csv('/Users/harika/Desktop/CSYE_7245/Assignment3/FastAPI/airflow/cmaps_data/{}_{}'.format(k,i)+'.txt',names=collist,sep='\s')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers.py", line 605, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers.py", line 463, in _read
    return parser.read(nrows)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers.py", line 1052, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers.py", line 2497, in read
    data = self._convert_data(data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers.py", line 2577, in _convert_data
    return self._convert_to_ndarrays(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers.py", line 1699, in _convert_to_ndarrays
    cvals, na_count = self._infer_types(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers.py", line 1753, in _infer_types
    result = lib.maybe_convert_numeric(values, na_values, False)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1241, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-04-02 00:22:36,541] {taskinstance.py:1496} INFO - Marking task as FAILED. dag_id=CMAPS_SNOWFLAKE_INGESTION, task_id=DataExtraction, execution_date=20210402T042022, start_date=20210402T042231, end_date=20210402T042236
[2021-04-02 00:22:36,638] {process_utils.py:66} INFO - Process psutil.Process(pid=9522, status='terminated', exitcode=1, started='00:22:31') (9522) terminated with exit code 1
