[2021-03-30 22:10:15,552] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: CMAPS_SNOWFLAKE_INGESTION.DataExtraction 2021-03-31T02:09:53+00:00 [queued]>
[2021-03-30 22:10:15,653] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: CMAPS_SNOWFLAKE_INGESTION.DataExtraction 2021-03-31T02:09:53+00:00 [queued]>
[2021-03-30 22:10:15,653] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-30 22:10:15,653] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-30 22:10:15,653] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-30 22:10:15,704] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): DataExtraction> on 2021-03-31T02:09:53+00:00
[2021-03-30 22:10:15,718] {standard_task_runner.py:52} INFO - Started process 25517 to run task
[2021-03-30 22:10:15,728] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'CMAPS_SNOWFLAKE_INGESTION', 'DataExtraction', '2021-03-31T02:09:53+00:00', '--job-id', '24', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/cmaps_pipeline.py', '--cfg-path', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmphox9wncb', '--error-file', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmpwyyw85cz']
[2021-03-30 22:10:15,732] {standard_task_runner.py:77} INFO - Job 24: Subtask DataExtraction
[2021-03-30 22:10:15,837] {logging_mixin.py:104} INFO - Running <TaskInstance: CMAPS_SNOWFLAKE_INGESTION.DataExtraction 2021-03-31T02:09:53+00:00 [running]> on host 152.1.168.192.in-addr.arpa
[2021-03-30 22:10:16,459] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=CMAPS_SNOWFLAKE_INGESTION
AIRFLOW_CTX_TASK_ID=DataExtraction
AIRFLOW_CTX_EXECUTION_DATE=2021-03-31T02:09:53+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-31T02:09:53+00:00
[2021-03-30 22:10:16,644] {logging_mixin.py:104} WARNING - /Users/harika/Desktop/CSYE_7245/Assignment3/FastAPI/airflow/dags/cmaps_pipeline.py:23 ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
[2021-03-30 22:10:16,670] {taskinstance.py:1455} ERROR - [Errno 2] No such file or directory: '../cmaps_data/train_FD001.txt'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/harika/Desktop/CSYE_7245/Assignment3/FastAPI/airflow/dags/cmaps_pipeline.py", line 23, in DataExtraction
    df1=pd.read_csv('../cmaps_data/{}_{}'.format(k,i)+'.txt',names=collist,sep='\s')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers.py", line 605, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers.py", line 814, in __init__
    self._engine = self._make_engine(self.engine)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers.py", line 1045, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers.py", line 2288, in __init__
    self._open_handles(f, kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers.py", line 1357, in _open_handles
    self.handles = get_handle(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../cmaps_data/train_FD001.txt'
[2021-03-30 22:10:16,698] {taskinstance.py:1496} INFO - Marking task as FAILED. dag_id=CMAPS_SNOWFLAKE_INGESTION, task_id=DataExtraction, execution_date=20210331T020953, start_date=20210331T021015, end_date=20210331T021016
[2021-03-30 22:10:16,854] {local_task_job.py:146} INFO - Task exited with return code 1
